version: '3'

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-console-raspina
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
    networks:
      - backend
  db:
    image: mysql:8.0.26
    container_name: db-console-raspina
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: raspina
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - backend
  php:
    build:
      context: .
      dockerfile: dockerFile
    container_name: php-console-raspina
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - backend
  composer:
    image: composer:latest
    container_name: composer-console-raspina
    restart: always
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backend
  npm:
    image: node:latest
    restart: always
    container_name: npm-console-raspina
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
  artisan:
    build:
      context: .
      dockerfile: dockerFile
    container_name: artisan-console-raspina
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: [ 'php','/var/www/html/artisan' ]
    networks:
      - backend
volumes:
  db_data: {}